argo/argo/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movement.urls')),
    path('', include('front.urls'))
]

argo/movement/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', include("django.contrib.auth.urls")),
    path('panel/', views.home, name='home'),
    path('panel/services/', views.services, name='services'),
    path('panel/edit_services/<id>', views.update_services, name='update-services'),
    path('panel/delete_services/<id>', views.delete_services, name='delete-services'),
    path('panel/gallery/', views.gallery, name='gallery'),
    path('panel/edit_gallery/<id>', views.edit_gallery, name='update-gallery'),
    path('panel/delete_gallery/<id>', views.delete_gallery, name='delete-gallery'),
    path('panel/about/', views.about, name='about'),
    path('panel/edit_about/<id>', views.update_about, name='update-about'),
    path('panel/delete_about/<id>', views.delete_about, name='delete-about'),
    path('panel/contact/', views.contact, name='contact'),
    path('panel/side_images/', views.side_images, name='side-images'),
    path('panel/edit_side_images/<id>', views.edit_side_images, name='update-side-images'),
]

argo/movement/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    username = models.CharField(max_length=50, unique=True, null=True)
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    avatar = models.ImageField(null=True, default="user.png")

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []


class HomePage(models.Model):
    side_picture = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=50, blank=True, null=True)
    text1 = models.TextField(max_length=1000, blank=True, null=True)
    text2 = models.TextField(max_length=1000, blank=True, null=True)
    text3 = models.TextField(max_length=1000, blank=True, null=True)


class ServicesPage(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    text = models.TextField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return f'{self.title} \n {self.text}'


class Gallery(models.Model):
    images = models.ImageField(upload_to='images',default="user.png")


class AboutPage(models.Model):
    text = models.TextField(max_length=1000, blank=True, null=True)


class ContactPage(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    mobile_number = models.CharField(max_length=100, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)


class SideImages(models.Model):
    images = models.ImageField(upload_to='images',default="user.png")

argo/movement/forms.py
from django.forms import ModelForm
from .models import HomePage, ServicesPage, Gallery, AboutPage, ContactPage,SideImages


class HomeForm(ModelForm):
    class Meta:
        model = HomePage
        fields = ['side_picture', 'title', 'text1', 'text2', 'text3']
        labels = {'side_picture': 'Image', 'title': 'title', 'text1': 'text1', 'text2': 'text2', 'text3': 'text3'}


class ServicesForm(ModelForm):
    class Meta:
        model = ServicesPage
        fields = ['title', 'text']
        labels = {'title': 'title', 'text': 'text'}



class GalleryForm(ModelForm):
    class Meta:
        model = Gallery
        fields = ('images',)


class AboutForm(ModelForm):
    class Meta:
        model = AboutPage
        fields = ['text']
        labels = {'text': 'text'}


class ContactForm(ModelForm):
    class Meta:
        model = ContactPage
        fields = ['title', 'address', 'mobile_number', 'email']
        labels = {'title': 'title', 'address': 'address', 'mobile_number': 'mobile_number', 'email': 'email'}


class SideImagesForm(ModelForm):
    class Meta:
        model = SideImages
        fields = ('images',)

argo/movement/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.decorators import login_required
from .models import HomePage, ServicesPage, Gallery, AboutPage, ContactPage,SideImages
from .forms import HomeForm, ServicesForm, GalleryForm, AboutForm, ContactForm,SideImagesForm
from django.template import loader
from django.http import HttpResponseRedirect
from django.http import HttpResponse


@login_required(login_url='login')
def home(request, id=1):
    if id:
        obj = HomePage.objects.get(id=id)
    else:
        obj = HomePage()

    if request.method == 'POST':
        form = HomeForm(request.POST, request.FILES, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = HomeForm(instance=obj)

    context = {
        'form': form, 'obj': obj
    }
    return render(request, 'movement/home.html', context)


@login_required(login_url='login')
def services(request):
    form = ServicesForm()
    servic = ServicesPage.objects.all()
    if request.method == 'POST':
        form = ServicesForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('services')
    context = {
        'form': form, 'servic': servic
    }
    return render(request, 'movement/services.html', context)


@login_required(login_url='login')
def update_services(request, id):
    servic = ServicesPage.objects.get(id=id)
    form = ServicesForm(instance=servic)
    template = loader.get_template('movement/update-service.html')
    if request.method == 'POST':
        form = ServicesForm(request.POST, instance=servic)
        if form.is_valid():
            form.save()
            return redirect('services')
    context = {
        'form': form, 'servic': servic
    }
    return HttpResponse(template.render(context, request))


@login_required(login_url='login')
def delete_services(request, id):
    servic = ServicesPage.objects.get(id=id)
    if request.method == "POST":
        servic.delete()
        return redirect('services')
    return render(request, 'movement/delete.html', {'obj': servic})



@login_required(login_url='login')
def gallery(request):
    form = GalleryForm()
    images = Gallery.objects.all()
    if request.method == 'POST':
        form = GalleryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('gallery')
    context = {
        'form': form,
        'images': images,
    }
    return render(request, 'movement/gallery.html', context)

@login_required(login_url='login')
def edit_gallery(request,id):
    gallery = Gallery.objects.get(id=id)
    form = GalleryForm(instance=gallery)
    template = loader.get_template('movement/update-'
                                   'gallery.html')
    if request.method == "POST":
        form = GalleryForm(request.POST, request.FILES, instance=gallery)
        if form.is_valid():
            form.save()
            return redirect('gallery')
    context = {'gallery':gallery,'form':form}
    return HttpResponse(template.render(context, request))

@login_required(login_url='login')
def delete_gallery(request,id):
    gallery = Gallery.objects.get(id=id)
    if request.method == "POST":
        gallery.delete()
        return redirect('gallery')
    return render(request, 'movement/delete.html', {'obj': gallery})


@login_required(login_url='login')
def about(request):
    form = AboutForm()
    abouts = AboutPage.objects.all()
    if request.method == 'POST':
        form = AboutForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('about')
    context = {
        'form': form,
        'abouts':abouts
    }
    return render(request, 'movement/about.html', context)


@login_required(login_url='login')
def update_about(request,id):
    about = AboutPage.objects.get(id=id)
    form = AboutForm(instance=about)
    template = loader.get_template('movement/update-about.html')
    if request.method == 'POST':
        form = AboutForm(request.POST, instance=about)
        if form.is_valid():
            form.save()
            return redirect('about')
    context = {
        'form': form, 'about': about
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='login')
def delete_about(request,id):
    abouts = AboutPage.objects.get(id=id)
    if request.method == "POST":
        abouts.delete()
        return redirect('about')
    return render(request, 'movement/delete.html', {'obj': abouts})


@login_required(login_url='login')
def contact(request, id=1):
    if id:
        obj = ContactPage.objects.get(id=id)
    else:
        obj = ContactPage()

    if request.method == 'POST':
        form = ContactForm(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('contact')
    else:
        form = ContactForm(instance=obj)
    context = {
        'form': form,
        'obj':obj
    }
    return render(request, 'movement/contact.html', context)

@login_required(login_url='login')
def side_images(request):
    form = SideImagesForm()
    images = SideImages.objects.all()
    # if request.method == 'POST':
    #     form = SideImagesForm(request.POST, request.FILES)
    #     if form.is_valid():
    #         form.save()
    #         return redirect('side-images')
    context = {
        'form': form,
        'images': images,
    }
    return render(request, 'movement/side_images.html', context)


@login_required(login_url='login')
def edit_side_images(request,id):
    side_image = SideImages.objects.get(id=id)
    form = SideImagesForm(instance=side_image)
    template = loader.get_template('movement/update-'
                                   'side_images.html')
    if request.method == "POST":
        form = SideImagesForm(request.POST, request.FILES, instance=side_image)
        if form.is_valid():
            form.save()
            return redirect('side-images')
    context = {'side_image':side_image,'form':form}
    return HttpResponse(template.render(context, request))

argo/movement/templates/movement/about.html
{% extends 'movement/base.html' %}

{% block content %}
<form class="main-form" method="post">
    {% csrf_token %}
    <h3>About Page</h3>
    <label for="id_text">About Text</label>
    <textarea name="text" class="form-control" cols="40" rows="10" maxlength="1000" id="id_text">
</textarea>
    <button type="submit" class="btn btn-success">Add</button>
</form>

<table class="table table-responsive-xl">
    <thead class="thead-dark" >
        <tr>
            <th>Text</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody class="table-bordered">
        <tr>
            {% for ab in abouts %}
                <tr>
                    <td>{{ab.text}}</td>
                    <td><a class="btn btn-warning" href="{% url 'update-about' ab.id %}">Edit</a></td>
                    <td><a class="btn btn-danger"  href="{% url 'delete-about' ab.id %}">delete</a></td>
                </tr>
            {% endfor %}
        </tr>
    </tbody>
</table>




{% endblock content %}

argo/movement/templates/movement/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}">  <!-- https://fontawesome.com/-->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">       <!-- https://dimsemenov.com/plugins/magnific-popup/ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">        <!-- https://getbootstrap.com/ -->
    <link rel="stylesheet" href="{% static 'slick/slick.min.css' %}">          <!-- https://kenwheeler.github.io/slick/ -->
    <link rel="stylesheet" href="{% static 'slick/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'movement/back.css' %}">


</head>
{% if user.is_authenticated == True %}
<body class="tm-section-wrap">

<div id="tm-sidebar" class="tm-sidebar">
    <nav class="tm-nav">
        <button class="navbar-toggler" type="button" onclick="onToggleAction()" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div>
            <div class="tm-brand-box">
                <a href="{% url 'home' %}" class="logo">
                    <img src="{% static 'img/vardos-logo-white.png' %}"  style="width: 450px;height: auto;" alt="">
                </a>
            </div>
            <ul id="tm-main-nav">
                <li class="nav-item">
                    <a href="{% url 'home' %}" class="nav-link">
                        <div class="triangle-right"></div>

                        Home
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'services' %}" class="nav-link">
                        <div class="triangle-right"></div>

                        Services
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'gallery' %}" class="nav-link">
                        <div class="triangle-right"></div>

                        Gallery
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'about' %}" class="nav-link">
                        <div class="triangle-right"></div>

                        About
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'contact' %}" class="nav-link">
                        <div class="triangle-right"></div>

                        Contact
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'side-images' %}" class="nav-link">
                        <div class="triangle-right"></div>

                        Side Images
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}?next=/login" class="nav-link">
                        <div class="triangle-right"></div>

                        Sign Out
                    </a>
                </li>
            </ul>
        </div>
        <footer class="mb-3 tm-mt-100">
        </footer>
    </nav>
</div>

<!--    <div class="navbar12">-->
<!--      <h3>Argo Admin</h3>-->
<!--      <ul>-->
<!--        <li><a href="{% url 'home' %}">Home</a></li>-->
<!--        <li><a href="{% url 'services' %}">Services</a></li>-->
<!--        <li><a href="{% url 'gallery' %}">Gallery</a></li>-->
<!--        <li><a href="{% url 'about' %}">About</a></li>-->
<!--        <li><a href="{% url 'contact' %}">Contact</a></li>-->
<!--        <li><a href="{% url 'side-images' %}">Side Images</a></li>-->
<!--        <li><a href="{% url 'logout' %}?next=/login">Sign Out</a></li>-->
<!--      </ul>-->

<!--    </div>-->

    {% block content %}


    {% endblock content %}

</body>
{% else %}
    <body>
        {% block login %}


        {% endblock login %}

    </body>

<!--    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>-->
<!--    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>-->
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>          <!-- https://jquery.com/ -->
    <script src="{% static 'js/jquery.singlePageNav.min.js' %}"></script>  <!-- https://github.com/ChrisWojcik/single-page-nav -->
    <script src="{% static 'js/parallax/parallax.min.js' %}"></script>     <!-- https://pixelcog.github.io/parallax.js/ -->
    <script src="{% static 'js/imagesloaded.pkgd.min.js' %}"></script>     <!-- https://imagesloaded.desandro.com/ -->
    <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>          <!-- https://isotope.metafizzy.co/ -->
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script> <!-- https://dimsemenov.com/plugins/magnific-popup/ -->
    <script src="{% static 'slick/slick.min.js' %}"></script>              <!-- https://kenwheeler.github.io/slick/ -->

{% endif %}
    <script src="{% static 'movement/script.js' %}"></script>

</html>

argo/movement/templates/movement/contact.html
{% extends 'movement/base.html' %}

{% block content %}

<form class="main-form" method="post">
    <h3>Contact Page</h3>
    {% csrf_token %}
    <label for="id_title" >Title</label>
    <input type="text" name="title" class="form-control" value="{{obj.title}}" maxlength="50" id="id_title">
    <label for="id_address">Address</label>
    <input type="text" name="address" class="form-control" value="{{obj.address}}" maxlength="100" id="id_address">
    <label for="id_mobile_number">Mobile Number</label>
    <input type="text" name="mobile_number" class="form-control" value="{{obj.mobile_number}}" maxlength="100" id="id_mobile_number">
    <label for="id_email">Email</label>
    <input type="email" name="address" class="form-control" value="{{obj.email}}" maxlength="100" id="id_email">

    <button type="submit" class="btn btn-success">Submit</button>
</form>
{% endblock content %}

argo/movement/templates/movement/delete.html
{% extends 'movement/base.html' %}
{% block content %}
<body class="buddy">
    <main class="delete-page">
        <div class="row"><div class="col" style="font-family:impact;color:#c73818;text-align:center;"><h1>Delete</h1></div></div>


        <div >
            <form class="main-form" method="POST" action="">
            <a href="{{request.META.HTTP_REFERER}}"></a>
                {% csrf_token %}
                <div class="form__group">
                    <p class="counter"><span style="color:#b50000;">Are you sure to Delete </span>"{{obj}}" ? </p>
                </div>


                <div class="for__group">
                    <a class="btn btn-secondary" id="no_btn" href="{{request.META.HTTP_REFERER}}">Back</a>
                    <input class="btn btn-danger"  id="delete_btn" type="submit" value="Delete" />
                </div>

            </form>
        </div>
    </main>
</body>

{% endblock content %}

argo/movement/templates/movement/gallery.html
{% extends 'movement/base.html' %}

{% block content %}
<form method="post" class="main-form" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Gallery</h3>
    <label for="images" class="drop-container">
      <span class="drop-title">Drop files here</span>
      or
      <input type="file" id="images" accept="image/*" name="images" required>
    </label>
    <button type="submit" class="btn btn-success">Add</button>
</form>


<div class="gallery">
    {% load static %}
    <table class="table table-responsive-xl">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody class="table-bordered">
            {% for image in images %}
                <tr>
                    <td style="width:30px;">
                        {{image.id}}
                    </td>
                    <td>
                        <img class="imagia" src="{% static 'images' %}/{{image.images}}" alt="{{ image.id }}">

                    </td>
                    <td style="width:60px;">
                        <a  class="btn btn-warning" href="{% url 'update-gallery' image.id %}">Edit</a>
                    </td>
                    <td style="width:60px;">
                        <a class="btn btn-danger" href="{% url 'delete-gallery' image.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>

    </table>


</div>


{% endblock content %}

argo/movement/templates/movement/home.html
{% extends 'movement/base.html' %}
{% block content %}

{% load static %}
<form method="post" class="main-form" enctype="multipart/form-data">
    {% csrf_token %}
    <h3>Home Page</h3>
    <div style="display: block; align-items: center;">
        <div class="form-group" style="justify-content: space-evenly">
            <label for="id_title" >Title</label>
            <input type="text" name="title" class="form-control" value="{{obj.title}}" maxlength="50" id="id_title">
        </div>
    </div>


    <div class="form-group">

            <label for="id_text1">Text 1</label>
            <textarea name="text1" cols="40" rows="10" class="form-control" maxlength="1000" id="id_text1">{{obj.text1}}</textarea>



            <label for="id_text2">Text 2</label>
            <textarea name="text2" cols="40" class="form-control" rows="10" maxlength="1000" id="id_text2">{{obj.text2}}</textarea>



            <label for="id_text3">Text 3</label>
            <textarea name="text3" cols="40" class="form-control" rows="10" maxlength="1000" id="id_text3">{{obj.text3}}</textarea>


        <button type="submit" class="btn btn-success">Submit</button>
    </div>


</form>




{% endblock content %}

argo/movement/templates/movement/services.html
{% extends 'movement/base.html' %}

{% block content %}
<form class="main-form" method="post">
    {% csrf_token %}
    <h3>Services</h3>
     <label for="id_text1">Title</label>
    <input type="text" name="title" class="form-control">

     <label for="id_text1">Text</label>
     <textarea name="text1" cols="40" rows="10" class="form-control" maxlength="1000" id="id_text1">{{obj.text1}}</textarea>

    <button type="submit" class="btn btn-success">Add</button>
</form>


<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>Text</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody class="table-bordered">
        {% for si in servic %}
            <tr>
                <td>{{si.title}}</td>
                <td>{{si.text}}</td>
                <td><a class="btn btn-warning" aria-label="Close" href="{% url 'update-services' si.id %}">Edit</a></td>
                <td><a class="btn btn-danger" aria-label="Close" href="{% url 'delete-services' si.id %}">Delete</a></td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

argo/movement/templates/movement/side_images.html
{% extends 'movement/base.html' %}

{% block content %}
<!--<form method="post" enctype="multipart/form-data">-->
<!--    {% csrf_token %}-->
<!--    {{ form.as_p }}-->
<!--    <input type="submit" value="Add">-->
<!--</form>-->


<div class="gallery">
    {% load static %}
    <h3>Side Images</h3>
    <table class="table table-responsive-xl">
        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Image</th>
                <th>Edit</th>
            </tr>
        </thead>
        <tbody class="table-bordered">
            {% for image in images %}
                <tr>
                    <td style="width:30px;">
                        {{image.id}}
                    </td>
                    <td>
                        <img class="imagia" src="{% static 'images' %}/{{image.images}}" alt="{{ image.id }}">

                    </td>
                    <td style="width:100px;">
                        <a class="btn btn-warning"  href="{% url 'update-side-images' image.id %}">Edit</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>

    </table>


</div>


{% endblock content %}

argo/movement/templates/movement/update-about.html
{% extends 'movement/base.html' %}

{% block content %}
<form class="main-form" method="post">
    {% csrf_token %}
    <label for="id_text">About Text</label>
    <textarea name="text" class="form-control" cols="40" rows="10" maxlength="1000" id="id_text">
        {{about.text}}
    </textarea>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

argo/movement/templates/movement/update-gallery.html
{% extends 'movement/base.html' %}

{% block content %}
{% load static %}
<form method="post" class="main-form" enctype="multipart/form-data">
    {% csrf_token %}
    <img class="imagia" src="{% static 'images' %}/{{gallery.images}}" alt="{{ gallery.id }}">
    <label for="images" class="drop-container">
      <span class="drop-title">Drop files here</span>
      or
      <input type="file" id="images" accept="image/*" name="images">
    </label>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

argo/movement/templates/movement/update-service.html
{% extends 'movement/base.html' %}

{% block content %}
<form class="main-form" method="post">
    {% csrf_token %}
    <label>Title</label>
    <input type="text" class="form-control" value="{{servic.title}}" maxlength="100" name="title">
    <label>Text</label>
    <textarea  maxlength="2000 " class="form-control" name="text">{{servic.text}}</textarea>

        <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}

argo/movement/templates/movement/update-side_images.html
{% extends 'movement/base.html' %}

{% block content %}
{% load static %}
<form method="post" class="main-form" enctype="multipart/form-data">
    {% csrf_token %}
    <img class="imagia" src="{% static 'images' %}/{{side_image.images}}" alt="{{ side_image.id }}">
    <label for="images" class="drop-container">
      <span class="drop-title">Drop files here</span>
      or
      <input type="file" id="images" accept="image/*" name="images">
    </label>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock content %}